config/routes.rb
StockHubBD::Application.routes.draw do
  devise_for :users, :controllers => {:omniauth_callbacks => 'users/omniauth_callbacks'} do
    ActiveAdmin.routes(self)
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  root 'stock_hubs#home'

  resources :stock_hubs do
    collection do
      get 'reports'
    end
  end

  resources :companies do
    member do
      resources :reporters do
        collection do
          get 'income_statement'
          get 'balance_sheet'
          get 'cash_flow_statement'
          get 'ratio_analysis'
          get 'comparative_scenario'
        end
      end
    end
  end

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user

	after_create :fetch_details



	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_facebook
		graph = Koala::Facebook::API.new(self.token)
		facebook_data = graph.get_object("me")
		self.first_name = facebook_data['first_name']
    self.last_name = facebook_data['last_name']
		self.save
	end

	def fetch_details_from_twitter

	end


	def fetch_details_from_github
	end


	def fetch_details_from_linkedin

	end

	def fetch_details_from_google_oauth2

	end
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates_presence_of :email

  has_many :authorizations

  def name
    [self.first_name+" "+self.last_name].join rescue ""
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0, 10]
        user.name = auth.info.name
        user.email = auth.info.email
        auth.provider == "twitter" ? user.save(:validate => false) : user.save
      end
      authorization.username = auth.info.nickname
      authorization.user_id = user.id
      authorization.save
    end
    authorization.user
  end
end

app/controllers/application_controller.rb
require 'query_report/helper'
class ApplicationController < ActionController::Base
  include QueryReport::Helper

  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end


  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params[:company]
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!
	def all
		p env["omniauth.auth"]
		user = User.from_omniauth(env["omniauth.auth"], current_user)
		if user.persisted?
			flash[:notice] = "You are in..!!! Go to edit profile to see the status for the accounts"
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	  def failure
      #handle you logic here..
      #and delegate to super.
      super
   end


	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :linkedin, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
end

app/controllers/reporters_controller.rb
class ReportersController < ApplicationController

  def income_statement
    query = Company.all

    reporter(query, report_name: "Income Statement Report") do
      column :name
    end
  end

  def balance_sheet
    query = Company.all

    reporter(query, report_name: "Balance Sheet Report") do
      column :id
      column :name
    end
  end

  def cash_flow_statement
    query = Company.all

    reporter(query, report_name: "Cash Flow Statement Report") do
      column :name
    end
  end

  def ratio_analysis
    query = Company.all

    reporter(query, report_name: "Ratio Analysis Report") do
      column :id
      column :name
    end
  end

  def comparative_scenario
    query = Company.all

    reporter(query, report_name: "Comparative Scenario Report") do
      column :name
    end
  end

end

app/controllers/stock_hubs_controller.rb
class StockHubsController < ApplicationController

  def home
    @companies = Company.all
  end

  def reports
    @company = Company.find(params[:company_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]


  def show
  end

  def edit
  end


  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def validate_authorization_for_user
    redirect_to root_path unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/reporters_helper.rb
module ReportersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StockHubBD</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div id="wrap">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "StockHubBD.com", root_path, :class => "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><%#= link_to current_user.name, current_user %></li>
              <li><a href="#">|</a></li>
              <li><%= link_to "Logout", destroy_user_session_path %></li>
          <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><a href="#">|</a></li>
              <li><%= link_to "Register", "#" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/stock_hubs/home.html.erb
<div class="row text-center">
  <h2>Company</h2>

  <div class="col-xs-offset-3">
    <div class="col-xs-8 input-group">
      <%= select_tag :company, options_from_collection_for_select(@companies, "id", "name"), class: "form-control", prompt: "Select Company" %>
    </div>
  </div>
</div>

<div class="clearfix">.</div>

<div class="row text-center">

  <div class="col-xs-4">
    <div class="caption">
      <h4 class="fundamental-analysis"><%= link_to "Fundamental Analysis", "#" %></h4>
    </div>
    <div class="thumbnail">
      <%= image_tag "large/800x600.gif" %>
    </div>
  </div>


  <div class="col-xs-4">
    <div class="caption">
      <h4 class="annual-report"><%= link_to "Purchase Annual Report", "#" %></h4>
    </div>
    <div class="thumbnail">
      <%= image_tag "large/800x600.gif" %>
    </div>
  </div>


  <div class="col-xs-4">
    <div class="caption">
      <h4 class="raw-data"><%= link_to "Purchase Raw Data", "#" %></h4>
    </div>
    <div class="thumbnail">
      <%= image_tag "large/800x600.gif" %>
    </div>
  </div>

</div>

<script type="text/javascript">
    $('select#company').on('change', function (e) {
        var optionSelected = $("option:selected", this);
        var valueSelected = this.value;
        $('.fundamental-analysis a').attr("href", "/stock_hubs/reports?company_id=" + valueSelected);
    });
</script>

app/views/stock_hubs/reports.html.erb
<div class="row text-center">
  <h4>
    <span><%= link_to "Income Statement", income_statement_reporters_path(@company, target_dom_id: :report_content), remote: true %></span>
    <span>|</span>
    <span><%= link_to "Balance Sheet", balance_sheet_reporters_path(@company, target_dom_id: :report_content), remote: true %></span>
    <span>|</span>
    <span><%= link_to "Cash Flow Statement", cash_flow_statement_reporters_path(@company, target_dom_id: :report_content), remote: true %></span>
    <span>|</span>
    <span><%= link_to "Ratio Analysis", ratio_analysis_reporters_path(@company, target_dom_id: :report_content), remote: true %></span>
    <span>|</span>
    <span><%= link_to "Comparative Scenario", comparative_scenario_reporters_path(@company, target_dom_id: :report_content), remote: true %></span>
  </h4>
</div>

<div class="row" id="report_content">
  <div class="text-center"><h2>Please Choose a Report!</h2></div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :about, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>
Connect Account



<% ['facebook', 'twitter', 'linkedin', 'google_oauth2'].each do |provider| %>

  <% if current_user.authorizations.pluck(:provider).include?(provider.to_s) %>
    <%= provider.to_s.titleize %> Connected
  <% else %>
      <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path('user', provider) %>
  <% end %>
<br/>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>